caja/urls.py
from django.conf.urls import patterns, include, url

from caja.views import *

urlpatterns = [

    url(r'^aperturacaja/$', AperturaCajaListView.as_view(), name='aperturacaja_lis'),
    url(r'^cierrecaja/$', CierreCajaListView.as_view(), name='cierrecaja_lis'),

    url(r'^$', caja_presentacion),
]

compra/urls.py
from django.conf.urls import patterns, include, url
from compra.views import *

urlpatterns = [

    url(r'^compra/(?P<pk>\d+)/detail/$', CompraDetailView.as_view(), name='compra_det'),
    url(r'^compra/$', CompraListView.as_view(), name='compra_lis'),
    url(r'^$', compra_presentacion),

]

ferresis/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/auth/', include("sistema.urls", namespace="cliente")),
    url(r'^admin/sistema/', include("sistema.urls", namespace="cliente")),

    url(r'^admin/caja/', include("caja.urls", namespace="cliente")),

    url(r'^admin/cliente/', include("cliente.urls", namespace="cliente")),
    url(r'^admin/proveedor/', include("proveedor.urls", namespace="proveedor")),
    url(r'^admin/producto/', include("producto.urls", namespace="producto")),
    url(r'^admin/presupuesto/', include("presupuesto.urls", namespace="presupuesto")),
    url(r'^admin/venta/', include("venta.urls", namespace="venta")),
    url(r'^admin/compra/', include("compra.urls", namespace="compra")),


    url(r'^admin/', admin.site.urls),

    url(r'^chaining/', include('smart_selects.urls')),
]

compra/models.py
from __future__ import unicode_literals
from django.db import models
from datetime import datetime

# Create your models here.
CONDICION = (('CONTADO', 'CONTADO'),('CREDITO','CREDITO'))

class Compra(models.Model):
	numero_factura = models.CharField(max_length=20, null=True, blank=True)
	proveedor = models.ForeignKey('proveedor.Proveedor', null=True, blank=True)
	condicion = models.CharField(choices=CONDICION, max_length = 10, default='CONTADO')
	fecha = models.DateField(default=datetime.now)
	descuento = models.DecimalField(max_digits=15,decimal_places=2, default=0)
	total = models.DecimalField(max_digits=15,decimal_places=2, default=0)
	carga_inicial = models.BooleanField(default=True)
	
	def __unicode__(self):
		return self.numero_factura

	class Meta:
		verbose_name = 'Compra'
		verbose_name_plural = 'Compras'

class DetalleCompra(models.Model):
	compra = models.ForeignKey(Compra)
	producto = models.ForeignKey('producto.Producto')
	cantidad = models.DecimalField(max_digits=15, decimal_places=2)
	precio = models.ForeignKey('producto.PrecioCompraProducto', verbose_name="unidad de medida")
	precio_unitario = models.DecimalField(max_digits=15, decimal_places=2)
	subtotal = models.DecimalField(max_digits=15, decimal_places=2)



compra/forms.py
from dal import autocomplete
from django import forms
from compra.models import Compra, DetalleCompra
from producto.models import *

class CompraForm(forms.ModelForm):
    class Meta:
        model = Compra
        fields = ('__all__')
        widgets = {
            "proveedor": autocomplete.ModelSelect2(url='/admin/proveedor/proveedor/proveedorautocomplete/'),
            "total":forms.TextInput(attrs={'style':'text-align:right','size':'12','class':'auto','data-a-sep':'.','data-a-dec':','}),
            "descuento":forms.TextInput(attrs={'style':'text-align:right','size':'12','class':'auto','data-a-sep':'.','data-a-dec':','}),
        }

    def __init__(self, *args, **kwargs):
        super(CompraForm, self).__init__(*args, **kwargs)
        self.fields['total'].widget.attrs['readonly'] = True

class DetalleCompraForm(forms.ModelForm):
    class Meta:
        model = DetalleCompra
        #fields = ('__all__')
        exclude = ['precio',]
        widgets = {
            "producto": autocomplete.ModelSelect2(url='/admin/producto/producto/productoautocomplete/'),
            "cantidad":forms.TextInput(attrs={'style':'text-align:right','size':'12','class':'auto subtotal_iterable','data-a-sep':'.','data-a-dec':','}),
            "precio_unitario":forms.TextInput(attrs={'style':'text-align:right','size':'12','class':'auto','data-a-sep':'.','data-a-dec':','}),
            "subtotal":forms.TextInput(attrs={'style':'text-align:right','size':'12','class':'auto','data-a-sep':'.','data-a-dec':','}),
        }

    precio = forms.IntegerField(widget=forms.Select(choices=(('','-------'),)), label="unidad de medida")

    def __init__(self, *args, **kwargs):
        super(DetalleCompraForm, self).__init__(*args, **kwargs)
        instance = getattr(self, 'instance', None)
        if instance and instance.pk:
            self.fields['precio'].widget.choices = (('','-------'),) + tuple(PrecioCompraProducto.objects.filter(producto_id = instance.producto.id).values_list('id','unidad_medida__nombre'))
            self.initial['precio'] = instance.precio_id

        self.fields['subtotal'].widget.attrs['readonly'] = True

    def save(self, commit=True):
        detalle = super(DetalleCompraForm, self).save(commit=False)
        detalle.precio_id = self.cleaned_data.get('precio')

        if commit:
            detalle.save()
        return detalle


compra/views.py
from django.contrib.auth.decorators import permission_required
from django.db.models import Q
from django.shortcuts import render_to_response, redirect
from django.template import RequestContext
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from proveedor.models import *
from compra.models import *

class CompraDetailView(DetailView):
    model = Compra
    template_name = "compra_detail.html"

    def get_context_data(self, **kwargs):
        context = super(CompraDetailView, self).get_context_data(**kwargs)
        context['detalles'] = DetalleCompra.objects.filter(compra_id=self.object.id)
        return context


class CompraListView(ListView):
    model = Compra
    template_name = "compra_list.html"
    paginate_by = 30

    def get_queryset(self):
        compras = Compra.objects.all()

        q = self.request.GET.get('q', '')
        if q != '':
            compras = compras.filter(numero_factura=q)

        proveedor_id = self.request.GET.get('proveedor_id', '')
        if proveedor_id != '':
            compras = compras.filter(proveedor_id=proveedor_id)


        return compras.order_by('-id')

    def get_context_data(self, **kwargs):
        context = super(CompraListView, self).get_context_data(**kwargs)
        context['q'] = self.request.GET.get('q', '')
        context['proveedores'] = Proveedor.objects.all()
        context['proveedor_id'] = int(self.request.GET.get('proveedor_id', '')) if (self.request.GET.get('proveedor_id', '') != '') else ''
        return context


def compra_presentacion(request):
    context = RequestContext(request)
    titulo = "VENTAS"
    descripcion = "."
    return render_to_response('admin/presentacion.html', {'titulo': titulo, 'descripcion': descripcion}, context)

compra/templates/compra_form.html
{% extends "admin/base_site.html" %}
{% load i18n admin_urls admin_static admin_modify %}

{% block extrahead %}{{ block.super }}
<script type="text/javascript" src="{% url 'admin:jsi18n' %}"></script>
{{ media }}
{% endblock %}

{% block extrajs %}
    <script type="text/javascript" src="{% static 'js/autoNumeric.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/decimales.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.maskedinput.min.js' %}"></script>
    <script type="text/javascript">
        jQuery(function($) {
            $('.auto').autoNumeric('init');
            $("#id_numero_factura").mask("999-999-9999999");
        });
    </script>

    {{ form.media.js }}
{% endblock %}



{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}" />{% endblock %}

{% block coltype %}colM{% endblock %}

{% block bodyclass %}{{ block.super }} app-{{ opts.app_label }} model-{{ opts.model_name }} change-form{% endblock %}

{% if not is_popup %}
{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
&rsaquo; <a href="{% url 'admin:app_list' app_label=opts.app_label %}">{{ opts.app_config.verbose_name }}</a>
&rsaquo; {% if has_change_permission %}<a href="{% url opts|admin_urlname:'changelist' %}">{{ opts.verbose_name_plural|capfirst }}</a>{% else %}{{ opts.verbose_name_plural|capfirst }}{% endif %}
&rsaquo; {% if add %}{% trans 'Add' %} {{ opts.verbose_name }}{% else %}{{ original|truncatewords:"18" }}{% endif %}
</div>
{% endblock %}
{% endif %}

{% block content %}<div id="content-main">
{% block object-tools %}
{% if change %}{% if not is_popup %}
  <ul class="object-tools">
    {% block object-tools-items %}
    <li>
        {% url opts|admin_urlname:'history' original.pk|admin_urlquote as history_url %}
        <a href="{% add_preserved_filters history_url %}" class="historylink">{% trans "History" %}</a>
    </li>
    {% if has_absolute_url %}<li><a href="{{ absolute_url }}" class="viewsitelink">{% trans "View on site" %}</a></li>{% endif %}
    {% endblock %}
  </ul>
{% endif %}{% endif %}
{% endblock %}
<form {% if has_file_field %}enctype="multipart/form-data" {% endif %}action="{{ form_url }}" method="post" id="{{ opts.model_name }}_form" novalidate>{% csrf_token %}{% block form_top %}{% endblock %}
<div>
{% if is_popup %}<input type="hidden" name="{{ is_popup_var }}" value="1" />{% endif %}
{% if to_field %}<input type="hidden" name="{{ to_field_var }}" value="{{ to_field }}" />{% endif %}
{% if save_on_top %}{% block submit_buttons_top %}{% submit_row %}{% endblock %}{% endif %}
{% if errors %}
    <p class="errornote">
    {% if errors|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
    </p>
    {{ adminform.form.non_field_errors }}
{% endif %}

{% block field_sets %}
{% for fieldset in adminform %}
  {% include "admin/includes/fieldset.html" %}
{% endfor %}
{% endblock %}

{% block after_field_sets %}{% endblock %}

{% block inline_field_sets %}
{% for inline_admin_formset in inline_admin_formsets %}
    {% include inline_admin_formset.opts.template %}
{% endfor %}
{% endblock %}

{% block after_related_objects %}{% endblock %}

{% block submit_buttons_bottom %}{% submit_row %}{% endblock %}

{% block admin_change_form_document_ready %}
    <script type="text/javascript">
        (function($) {
            $(document).ready(function() {
                $('.add-another').click(function(e) {
                    e.preventDefault();
                    var event = $.Event('django:add-another-related');
                    $(this).trigger(event);
                    if (!event.isDefaultPrevented()) {
                        showAddAnotherPopup(this);
                    }
                });
                $('.related-lookup').click(function(e) {
                    e.preventDefault();
                    var event = $.Event('django:lookup-related');
                    $(this).trigger(event);
                    if (!event.isDefaultPrevented()) {
                        showRelatedObjectLookupPopup(this);
                    }
                });


                // quitar coma decimal y separadores de miles antes del submit
                $('form input[type=submit]').click(function(e) {
                    $('.auto').each(function (){
                        $(this).val(($(this).val()!='')?unformat(document.getElementById(this.id.toString())):'');
                    });
                });



                // recargar el plugin de autonumeric al crear una nueva fila
                $('.add-row').click(function() {
                    jQuery(function($) {
                        $('.auto').autoNumeric('init');
                    });
                });

                // recalcular totales al marcar o desmarcar algo como borrado
                $('form input[type=checkbox]').click(function(e) {
                    calcular_total();
                });

                // recalcular totales al borrar un item de un detalle no guardador (con botoncito 'x')
                $('.inline-deletelink').click(function() {
                    calcular_total();
                });

                // calcular totales al editar campos numericos
                $('.auto').keyup(function(){
                    calcular_total();
                });

                $('select').change(function(){

                    vector = $(this).attr("id").split("-");

                    if( (vector[0] == "id_detallecompra_set") && (vector[2] == "precio") ){
                        var optionSelected = $(this).find("option:selected");
                        var valueSelected  = optionSelected.val();
                        console.log(valueSelected)
                        if(!valueSelected){
                            $("#id_detallecompra_set-" + vector[1] + "-precio_unitario").val("");
                            calcular_total();
                            return
                        }
                        $.ajax({
                            data : {'preciocompra_id' : valueSelected },
                            url : "/admin/producto/getpreciocompra/",
                            type : "get",
                            success : function(data){
                                $("#id_detallecompra_set-" + vector[1] + "-precio_unitario").val(data[0].precio);
                                calcular_total();
                            }
                        });
                    }

                    if( (vector[0] == "id_detallecompra_set") && (vector[2] == "producto") ){
                        var optionSelected = $(this).find("option:selected");
                        var valueSelected  = optionSelected.val();
                        if(!valueSelected){
                            $("#id_detallecompra_set-" + vector[1] + "-precio option").remove();
                            $("#id_detallecompra_set-" + vector[1] + "-precio").append("<option value=\"\" selected=\"selected\">---------</option>");

                            $("#id_detallecompra_set-" + vector[1] + "-precio_unitario").val("");
                            calcular_total();

                            return
                        }
                        $.ajax({
                            data : {'producto_id' : valueSelected },
                            url : "/admin/producto/getlistaprecioscompra",
                            type : "get",
                            success : function(data){

                                console.log(data);
                                $("#id_detallecompra_set-" + vector[1] + "-precio option").remove();
                                $("#id_detallecompra_set-" + vector[1] + "-precio").append("<option value=\"\" selected=\"selected\">---------</option>");
                                for (var i = 0; i < data.length; i++) {
                                    $("#id_detallecompra_set-" + vector[1] + "-precio").append('<option value='+ data[i].id +'>'+ data[i].precio +'</option>');
                                }
                            }
                        });
                    }


                });


            {% if adminform and add %}
                $('form#{{ opts.model_name }}_form :input:visible:enabled:first').focus()
            {% endif %}
            });
        })(django.jQuery);


        /*
            calculo de los totales
        */
        function calcular_total(){
            var total_general = 0;
            $('.subtotal_iterable').each(function(){
                var vector = $(this).attr("id").split("-");

                var cantidad = ($('#'+vector[0]+'-'+vector[1]+'-cantidad').val()!='')?unformat(document.getElementById(vector[0]+'-'+vector[1]+'-cantidad')):'0';

                var precio = ($('#'+vector[0]+'-'+vector[1]+'-precio_unitario').val()!='')?unformat(document.getElementById(vector[0]+'-'+vector[1]+'-precio_unitario')):'0';

                //var descuento = ($('#'+vector[0]+'-'+vector[1]+'-descuento').val()!='')?unformat(document.getElementById(vector[0]+'-'+vector[1]+'-descuento')):'0';

                //var subtotal = ( (parseFloat(cantidad) * parseFloat(precio)) - parseFloat(descuento) )
                var subtotal = parseFloat(cantidad) * parseFloat(precio)

                if( (cantidad!='0') && (precio!='0') ){
                    $('#'+vector[0]+'-'+vector[1]+'-subtotal').val( parseFloat(subtotal).toString().replace(".",",") );
                    format(document.getElementById(vector[0]+'-'+vector[1]+'-subtotal'));
                } else {
                    $('#'+vector[0]+'-'+vector[1]+'-subtotal').val('');
                }

                if($('#'+vector[0]+'-'+vector[1]+'-DELETE').is(':checked')==false){
                    total_general += subtotal
                }
            });

            var descuento_general = ($('#id_descuento').val()!='')?unformat(document.getElementById('id_descuento')):'0';

            total_general = parseFloat(total_general) - parseFloat(descuento_general)

            $('#id_total').val( parseFloat(total_general).toString().replace(".",",") );
            format(document.getElementById('id_total'));
        }

    </script>
{% endblock %}

{# JavaScript for prepopulated fields #}
{% prepopulated_fields_js %}

</div>
</form></div>
{% endblock %}

compra/templates/compra_list.html
{% extends 'admin/base_site.html' %}
{% load i18n admin_static %}
{% load humanize %}
{% load my_tags %}

{% block extrastyle %}
    <link rel="stylesheet" href="{% static 'chosen/chosen.css' %}">
    <link rel="stylesheet" href="{% static 'chosen/docsupport/prism.css' %}">
{% endblock %}

{% block extrajs %}
    <script src="{% static 'chosen/chosen.jquery.js' %}"></script>
    <script src="{% static 'chosen/docsupport/prism.js' %}"></script>

    <script type="text/javascript" src="{% static 'js/jquery.maskedinput.min.js' %}"></script>
    <script type="text/javascript">
        $(".chosen-select").chosen({
            disable_search_threshold: 0,
            no_results_text: "Sin resultados..",
            width: "300px",
            allow_single_deselect: true
        });
        $('.chosen-select').trigger('chosen:updated');
    </script>
    <script>
        jQuery(function($) {
            $("#id_numero_de_factura").mask("999-999-9999999");
        });
    </script>
{% endblock %}

{% block content %}
    <form class="form" method="get">
        <h1>Lista de compras</h1>
        <center>
            <dl>
                <table class="table-filter table table-bordered table-stripped">
                    <tbody>
                    <tr>
                        <th style="vertical-align:middle">
                            <strong> Numero de Factura:</strong>
                        </th>
                        <td style="vertical-align:middle">
                            <input type="text"   id="id_numero_de_factura" class="search-query" placeholder="Numero de Factura.." name="q" value="{{ q }}">
                        </td>

                        <th style="vertical-align:middle">
                            <strong> Proveedor:</strong>
                        </th>
                        <td style="vertical-align:middle">
                            <select class="chosen-select" data-placeholder="Seleccione un proveedor.." name="proveedor_id" value="{{ proveedor_id }}" onchange="this.form.submit();">
                                <option value=""></option>
                                {% for proveedor in proveedores %}
                                    <option {% if proveedor.pk == proveedor_id %} selected {% endif %} value="{{ proveedor.id }}">{{ proveedor.nombre }}</option>
                                {% endfor %}
                            </select>
                        </td>

                        <th style="border-top :3px solid white; border-right :3px solid white; border-bottom :3px solid white;">
                            <a class="btn btn-info" href="/admin/compra/compra/" title="Limpiar Filtros">
                                <i class="fa fa-undo"></i>
                            </a>
                            <input type="submit" value="Buscar" class="btn btn-success" hidden="hidden" style="display: none">
                        </th>
                    </tr>
                    </tbody>
                </table>
            </dl>
        </center>

        <div id="next_button" align="right">
            {% if perms.compra.add_compra %}
                <button type="button" class="btn btn-primary" onclick="location.href='/admin/compra/compra/add/';" title="Agregar compra">
                    <span class="glyphicon glyphicon-plus"></span>
                </button>
            {% endif %}

            <!--
            <button onclick="this.form.submit();" class="btn btn-success" name="excel" value="excel" type="submit" title="Exportar a Excel">
                <i class="fa fa-file-excel-o"></i>
            </button>
            -->
        </div>
    </form>


    <br/>

    <div align="center">
        <table id="result_list" class="table table-striped table-filter">
            <thead>
            <tr>
                <th>Fecha</th>
                <th>Factura</th>
                <th>Proveedor</th>
                <th>Total</th>
                <th>Acciones</th>
            </tr>
            </thead>

            <tbody>
            {% for compra in object_list %}
                <tr>
                    <td>{{ compra.fecha }}</td>
                    <td>{{ compra.numero_factura }}</td>
                    <td>{{ compra.proveedor }}</td>
                    <td>{{ compra.total|floatformat:"0"|intcomma|default_if_none:"&nbsp;" }}</td>

                    <td>
                        {% if perms.compra.change_compra %}
                        <button type="button" class="btn btn-warning btn-xs" onclick="location.href='/admin/compra/compra/{{ compra.id }}/';" title="Editar">
                            <i class="fa fa-pencil"></i>
                        </button>
                        {% endif %}

                        {% if perms.compra.delete_compra %}
                        <button type="button" class="btn btn-danger btn-xs" onclick="location.href='/admin/compra/compra/{{ compra.id }}/delete/';" title="Borrar">
                            <i class="fa fa-minus"></i>
                        </button>
                        {% endif %}

                        <!--
                        <button type="button" class="btn btn-info btn-xs" onclick="location.href='/admin/compra/compra/{{ compra.id }}/detail/';" title="Detalle">
                            <i class="fa fa-list-ol"></i>
                        </button>
                        -->
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    {% if is_paginated %}
        <table class="table">
            <td>
                <center>
                    <ul class="pagination pagination-sm">
                        {% if page_obj.has_previous %}
                            <li class="previous">
                                <a href="/admin/compra/compra/?page={{ page_obj.previous_page_number }}&q={{ q }}&proveedor_id={{ proveedor_id }}">
                                    <span aria-hidden="true">&larr;</span> Primera
                                </a>
                            </li>

                            <li>
                                <a href="/admin/compra/compra/?page={{ page_obj.previous_page_number }}&q={{ q }}&proveedor_id={{ proveedor_id }}">
                                    Anterior
                                </a>
                            </li>
                        {% endif %}

                        {% for page in page_obj.paginator.page_range|paginator_delimiter:page_obj.number %}
                            <li>
                                <a {% if page == page_obj.number %} class="active" style="background-color:#DD4814;color:white;" {% endif %} href="/admin/compra/compra/?page={{ page }}&q={{ q }}&proveedor_id={{ proveedor_id }}">
                                    {{ page }}
                                </a>
                            </li>
                        {% endfor %}

                        {% if page_obj.has_next %}
                            <li>
                                <a href="/admin/compra/compra/?page={{ page_obj.next_page_number }}&q={{ q }}&proveedor_id={{ proveedor_id }}">
                                    Siguiente
                                </a>
                            </li>

                            <li class="next">
                                <a href="/admin/compra/compra/?page={{ page_obj.paginator.num_pages}}&q={{ q }}&proveedor_id={{ proveedor_id }}">
                                    &Uacute;ltima <span aria-hidden="true">&rarr;</span>
                                </a>
                            </li>
                        {% endif %}

                    </ul>
                </center>
            </td>
            <th>
                Pag. {{ page_obj.number }}/{{ page_obj.paginator.num_pages }}
            </th>
        </table>
    {% endif %}
{% endblock %}