caja/urls.py
from django.conf.urls import patterns, include, url

from caja.views import *

urlpatterns = [

    url(r'^aperturacaja/$', AperturaCajaListView.as_view(), name='aperturacaja_lis'),
    url(r'^cierrecaja/$', CierreCajaListView.as_view(), name='cierrecaja_lis'),

    url(r'^$', caja_presentacion),
]

ferresis/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/auth/', include("sistema.urls", namespace="cliente")),
    url(r'^admin/sistema/', include("sistema.urls", namespace="cliente")),

    url(r'^admin/caja/', include("caja.urls", namespace="cliente")),

    url(r'^admin/cliente/', include("cliente.urls", namespace="cliente")),
    url(r'^admin/proveedor/', include("proveedor.urls", namespace="proveedor")),
    url(r'^admin/producto/', include("producto.urls", namespace="producto")),
    url(r'^admin/presupuesto/', include("presupuesto.urls", namespace="presupuesto")),
    url(r'^admin/venta/', include("venta.urls", namespace="venta")),
    url(r'^admin/compra/', include("compra.urls", namespace="compra")),


    url(r'^admin/', admin.site.urls),

    url(r'^chaining/', include('smart_selects.urls')),
]

producto/urls.py
from django.conf.urls import patterns, include, url
from producto.views import *
from producto.autocomplete import *
from producto.ajax import *


urlpatterns = [
    url(
        'productoautocomplete/$',
        ProductoAutocomplete.as_view(),
        name='producto-autocomplete',
    ),

    url(r'^getprecioventa/$',get_precioventa),
    url('getlistapreciosventa/$',get_listapreciosventa),

    url(r'^getpreciocompra/$',get_preciocompra),
    url('getlistaprecioscompra/$',get_listaprecioscompra),

    url(r'^categoria/$', CategoriaListView.as_view(),name='categoria_lis'),
    url(r'^insercioninmediata/$', InsercionInmediataListView.as_view(),name='insercioninmeadiata_lis'),
    url(r'^sustraccioninmediata/$', SustraccionInmediataListView.as_view(),name='sustraccioninmeadiata_lis'),

    url(r'^unidadmedida/$', UnidadMedidaListView.as_view(),name='unidadmedida_lis'),

    url(r'^producto/$', ProductoListView.as_view(),name='producto_lis'),

    url(r'^corrompidos/$', listar_corrompidos),

    url(r'^$', producto_presentacion),

]

producto/models.py
from __future__ import unicode_literals

from django.db import models
from proveedor.models import Proveedor

from venta.models import *
from compra.models import *

from extra.globals import *

# Create your models here.
class UnidadMedida(models.Model):
	nombre = models.CharField(max_length=50,unique=True)
	abreviatura = models.CharField(max_length=10,unique=True)

	def __unicode__(self):
		return self.nombre

	class Meta:
		verbose_name = 'Unidad de medida'
		verbose_name_plural = 'Unidades de medida'


class Categoria(models.Model):
	nombre = models.CharField(max_length=100, unique=True)

	def __unicode__(self):
		return self.nombre

	class Meta:
		verbose_name = 'Categoria'
		verbose_name_plural = 'Categorias'

IVA = (('IVA10', 'IVA 10%'), ('IVA5', 'IVA 5%'), ('EXENTA', 'EXENTA'))

class Producto(models.Model):
	codigo = models.CharField(max_length=50,unique=True)
	nombre = models.CharField(max_length=200,unique=True)
	categoria = models.ForeignKey(Categoria)
	unidad_medida = models.ForeignKey(UnidadMedida)
	iva = models.CharField("IVA",max_length=10, choices=IVA, default='IVA10')

	proveedor = models.ManyToManyField(Proveedor, blank=True)

	def __unicode__(self):
		return self.nombre

	class Meta:
		permissions = (
			("view_producto", "Puede ver la lista de productos"),
		)
		verbose_name = 'Producto'
		verbose_name_plural = 'Productos'

	def get_cantidad(self):

		vendidos = DetalleVenta.objects.filter(producto_id = self.id)
		cantidad_vendida = 0
		print self.id
		precio_venta = PrecioVentaProducto.objects.filter(producto_id = self.id)
		precio_venta = precio_venta[0]


		print "111111"

		for vendido in vendidos:
			if vendido.precio == precio_venta:
				cantidad_vendida = cantidad_vendida + vendido.cantidad
			else:
				cantidad_vendida = cantidad_vendida + (vendido.cantidad*vendido.precio.factor_conversion)


		comprados = DetalleCompra.objects.filter(producto_id = self.id, compra__carga_inicial=True)
		cantidad_comprada = 0
		precio_compra = PrecioCompraProducto.objects.filter(producto_id = self.id)[0]
		for comprado in comprados:
			if comprado.precio == precio_compra:
				cantidad_comprada = cantidad_comprada + comprado.cantidad
			else:
				cantidad_comprada = cantidad_comprada + (comprado.cantidad*comprado.precio.factor_conversion)

		insertados = InsercionInmediata.objects.filter(producto_id = self.id)
		cantidad_insertada = 0
		for insertado in insertados:
			cantidad_insertada = cantidad_insertada + insertado.cantidad

		sustraidos = SustraccionInmediata.objects.filter(producto_id = self.id)
		cantidad_sustraida = 0
		for sustraido in sustraidos:
			cantidad_sustraida = cantidad_sustraida + sustraido.cantidad

		stock = cantidad_comprada + cantidad_insertada - cantidad_vendida - cantidad_sustraida

		return stock


	def get_precio_venta(self):
		return (PrecioVentaProducto.objects.filter(producto_id = self.id)[0]).precio_venta

	def get_precio_compra(self):
		return (PrecioCompraProducto.objects.filter(producto_id = self.id)[0]).precio_compra
	

class PrecioVentaProducto(models.Model):
	class Meta:
		verbose_name = 'Otro precio de venta'
		verbose_name_plural = 'Otros precios de venta'

	producto = models.ForeignKey(Producto)
	unidad_medida = models.ForeignKey(UnidadMedida)

	precio_venta = models.DecimalField("Precio de venta", max_digits=15,decimal_places=2)
	factor_conversion = models.DecimalField("Factor de conversion", max_digits=15,decimal_places=2, help_text="Numero a multiplicar para convertir en la unidad de medida principal")

	def __unicode__(self):
		return self.unidad_medida.abreviatura 

	def __str__(self):
		return separador_de_miles(self.precio_venta) + " Gs/" + self.unidad_medida.abreviatura 




class PrecioCompraProducto(models.Model):
	class Meta:
		verbose_name = 'otro precio de compra'
		verbose_name_plural = 'otros precios de compra'

	producto = models.ForeignKey(Producto)
	unidad_medida = models.ForeignKey(UnidadMedida)

	precio_compra = models.DecimalField("Precio de compra", max_digits=15,decimal_places=2)
	factor_conversion = models.DecimalField("Factor de conversion", max_digits=15,decimal_places=2, help_text="Numero a multiplicar para convertir en la unidad de medida principal")

	def __unicode__(self):
		return self.unidad_medida.abreviatura 

	def __str__(self):
		return separador_de_miles(self.precio_compra) + " Gs/" + self.unidad_medida.abreviatura 





class InsercionInmediata(models.Model):
	producto = models.ForeignKey(Producto)
	cantidad = models.DecimalField(max_digits=15,decimal_places=2, default=0)
	observacion = models.CharField(max_length=50, blank=True)
	fecha_hora = models.DateTimeField(auto_now_add=True, blank=True)

	class Meta:
		verbose_name = 'Insercion Inmediata'
		verbose_name_plural = 'Inserciones Inmediatas'


class SustraccionInmediata(models.Model):
	producto = models.ForeignKey(Producto)
	cantidad = models.DecimalField(max_digits=15,decimal_places=2, default=0)
	observacion = models.CharField(max_length=50, blank=True)
	fecha_hora = models.DateTimeField(auto_now_add=True, blank=True)

	class Meta:
		verbose_name = 'Sustraccion Inmediata'
		verbose_name_plural = 'Sustracciones Inmediatas'



producto/forms.py
from dal import autocomplete
from django import forms
from producto.models import *


class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = ('__all__')

    precio_venta = forms.IntegerField(widget=forms.TextInput(attrs={'style':'text-align:right','size':'12','class':'auto','data-a-sep':'.','data-a-dec':','}), required=True, label="Precio de venta")
    precio_compra = forms.IntegerField(widget=forms.TextInput(attrs={'style':'text-align:right','size':'12','class':'auto','data-a-sep':'.','data-a-dec':','}), required=True, label="Precio de compra")
    unidad_medida = forms.ModelChoiceField(queryset=UnidadMedida.objects.all(), required=True, label='Unidad de medida')

    def __init__(self, *args, **kwargs):
        super(ProductoForm, self).__init__(*args, **kwargs)
        instance = getattr(self, 'instance', None)
        if instance and instance.pk:
            self.initial['precio_venta'] = (PrecioVentaProducto.objects.filter(producto_id=instance.id)[0]).precio_venta
            self.initial['precio_compra'] = (PrecioCompraProducto.objects.filter(producto_id=instance.id)[0]).precio_compra

class InsercionInmediataForm(forms.ModelForm):
    class Meta:
        model = InsercionInmediata
        fields = ('__all__')
        widgets = {
        	"producto": autocomplete.ModelSelect2(url='/admin/producto/producto/productoautocomplete/'),
            "cantidad":forms.TextInput(attrs={'style':'text-align:right','size':'12','class':'auto','data-a-sep':'.','data-a-dec':','}),
       	}

class SustraccionInmediataForm(forms.ModelForm):
    class Meta:
        model = SustraccionInmediata
        fields = ('__all__')
        widgets = {
        	"producto": autocomplete.ModelSelect2(url='/admin/producto/producto/productoautocomplete/'),
            "cantidad":forms.TextInput(attrs={'style':'text-align:right','size':'12','class':'auto','data-a-sep':'.','data-a-dec':','}),
        }
        
class PrecioVentaProductoForm(forms.ModelForm):
    class Meta:
        model = PrecioVentaProducto
        fields = ('__all__')
        widgets = {
            "precio_venta":forms.TextInput(attrs={'style':'text-align:right','size':'12','class':'auto','data-a-sep':'.','data-a-dec':','}),
            "factor_conversion":forms.TextInput(attrs={'style':'text-align:right','size':'12','class':'auto','data-a-sep':'.','data-a-dec':','}),
       	}
    unidad_medida = forms.ModelChoiceField(queryset=UnidadMedida.objects.all(), required=True, label='Unidad de medida')

class PrecioCompraProductoForm(forms.ModelForm):
    class Meta:
        model = PrecioCompraProducto
        fields = ('__all__')
        widgets = {
            "precio_compra":forms.TextInput(attrs={'style':'text-align:right','size':'12','class':'auto','data-a-sep':'.','data-a-dec':','}),
            "factor_conversion":forms.TextInput(attrs={'style':'text-align:right','size':'12','class':'auto','data-a-sep':'.','data-a-dec':','}),
        }
    unidad_medida = forms.ModelChoiceField(queryset=UnidadMedida.objects.all(), required=True, label='Unidad de medida')

producto/views.py
from django.shortcuts import render, render_to_response
from django.template import RequestContext
from django.views.generic.detail import DetailView
from dal import autocomplete
from django.db.models import Q
from producto.models import *

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView

from django.utils.decorators import method_decorator
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import permission_required
from extra.globals import *

# Create your views here.

class ProductoListView(ListView):
    model = Producto
    paginate_by = 30
    template_name = "producto_list.html"

    def get_queryset(self):
        q=self.request.GET.get('q','')
        return Producto.objects.filter( Q(codigo__istartswith=q) | Q(nombre__icontains=q)).order_by('id')

    def get_context_data(self, **kwargs):
        context = super(ProductoListView, self).get_context_data(**kwargs)
        context['q']=self.request.GET.get('q','')
        return context

    def render_to_response(self, context, **response_kwargs):
        if 'excel' in self.request.GET.get('excel', ''): 
           
            lista_datos=[]
            datos = self.get_queryset()
            for dato in datos:
                lista_datos.append([dato.codigo, 
                                    dato.nombre,
                                    separador_de_miles(dato.get_cantidad()),
                                    separador_de_miles(dato.get_precio_compra()),
                                    separador_de_miles(dato.get_precio_venta())
                                    ])
           
            titulos=['Codigo','Nombre','Cantidad','Precio de compra','Precio de venta']
            return listview_to_excel(lista_datos,'Producto',titulos)
        else:
            return super(ProductoListView, self).render_to_response(context, **response_kwargs)

    @method_decorator(staff_member_required)
    def dispatch(self, *args, **kwargs):
        return super(ProductoListView, self).dispatch(*args, **kwargs)


class CategoriaListView(ListView):
    model = Categoria
    template_name = "categoria_list.html"
    paginate_by = 30

    def get_queryset(self):
        categorias = Categoria.objects.all()

        q = self.request.GET.get('q', '')
        if q != '':
            categorias = categorias.filter( nombre__icontains=q )

        return categorias.order_by('-id')

    def get_context_data(self, **kwargs):
        context = super(CategoriaListView, self).get_context_data(**kwargs)
        context['q'] = self.request.GET.get('q', '')
        return context

    @method_decorator(staff_member_required)
    def dispatch(self, *args, **kwargs):
        return super(CategoriaListView, self).dispatch(*args, **kwargs)

class UnidadMedidaListView(ListView):
    model = UnidadMedida
    template_name = "unidadmedida_list.html"
    paginate_by = 30

    def get_queryset(self):
        unidadesmedidas = UnidadMedida.objects.all()

        q = self.request.GET.get('q', '')
        if q != '':
            unidadesmedidas = unidadesmedidas.filter( nombre__icontains=q )

        return unidadesmedidas.order_by('-id')

    def get_context_data(self, **kwargs):
        context = super(UnidadMedidaListView, self).get_context_data(**kwargs)
        context['q'] = self.request.GET.get('q', '')
        return context

    @method_decorator(staff_member_required)
    def dispatch(self, *args, **kwargs):
        return super(UnidadMedidaListView, self).dispatch(*args, **kwargs)


class InsercionInmediataListView(ListView):
    model = InsercionInmediata
    template_name = "insercioninmediata_list.html"
    paginate_by = 30

    def get_queryset(self):
        insercionesinmediatas = InsercionInmediata.objects.all()

        q = self.request.GET.get('q', '')
        if q != '':
            insercionesinmediatas = insercionesinmediatas.filter( Q(producto__nombre__icontains=q) | Q(producto__codigo__istartswith=q) )

        return insercionesinmediatas.order_by('-id')

    def get_context_data(self, **kwargs):
        context = super(InsercionInmediataListView, self).get_context_data(**kwargs)
        context['q'] = self.request.GET.get('q', '')
        return context

    @method_decorator(staff_member_required)
    def dispatch(self, *args, **kwargs):
        return super(InsercionInmediataListView, self).dispatch(*args, **kwargs)


class SustraccionInmediataListView(ListView):
    model = SustraccionInmediata
    template_name = "sustraccioninmediata_list.html"
    paginate_by = 30

    def get_queryset(self):
        sustraccionesinmediatas = SustraccionInmediata.objects.all()

        q = self.request.GET.get('q', '')
        if q != '':
            sustraccionesinmediatas = sustraccionesinmediatas.filter( Q(producto__nombre__icontains=q) | Q(producto__codigo__istartswith=q) )

        return sustraccionesinmediatas.order_by('-id')

    def get_context_data(self, **kwargs):
        context = super(SustraccionInmediataListView, self).get_context_data(**kwargs)
        context['q'] = self.request.GET.get('q', '')
        return context

    @method_decorator(staff_member_required)
    def dispatch(self, *args, **kwargs):
        return super(SustraccionInmediataListView, self).dispatch(*args, **kwargs)

def producto_presentacion(request):
    context = RequestContext(request)
    titulo="PRODUCTOS"
    descripcion=".."
    return render_to_response('admin/presentacion.html', {'titulo': titulo, 'descripcion': descripcion}, context)


def listar_corrompidos(request):
    context = RequestContext(request)
    productos = Producto.objects.all().order_by('id')
    precio_compra = PrecioVentaProducto.objects.all().order_by('producto_id')

    return render_to_response('corrompidos.html', {'productos': productos, 'precio_compra':precio_compra}, context)

producto/templates/categoria_list.html
{% extends 'admin/base_site.html' %}
{% load i18n admin_static %}
{% load humanize %}
{% load my_tags %}

{% block extrastyle %}
    <link rel="stylesheet" href="{% static 'chosen/chosen.css' %}">
    <link rel="stylesheet" href="{% static 'chosen/docsupport/prism.css' %}">
{% endblock %}

{% block extrajs %}
    <script src="{% static 'chosen/chosen.jquery.js' %}"></script>
    <script src="{% static 'chosen/docsupport/prism.js' %}"></script>

    <script type="text/javascript">
        $(".chosen-select").chosen({
            disable_search_threshold: 0,
            no_results_text: "Sin resultados..",
            width: "300px",
            allow_single_deselect: true
        });
        $('.chosen-select').trigger('chosen:updated');
    </script>
{% endblock %}

{% block content %}
	<form class="form" method="get">
		<h1>Lista de Categorias de productos</h1>
		<center>
			<dl>
				<table class="table-filter table table-bordered table-stripped">
					<tbody>
						<tr>

							<th style="vertical-align:middle">
								<strong> Categoria:</strong>
							</th>
							<td style="vertical-align:middle">
								<input type="text" class="search-query" placeholder="Nombre" name="q" value="{{ q }}">
							</td>

							<th style="border-top :3px solid white; border-right :3px solid white; border-bottom :3px solid white;">
								<a class="btn btn-info" href="/admin/producto/categoria" title="Limpiar Filtros">
									<i class="fa fa-undo"></i>
								</a>
								<input type="submit" value="Buscar" class="btn btn-success" hidden="hidden" style="display: none">
							</th>
						</tr>
					</tbody>
				</table>
			</dl>
		</center>
		
		<div id="next_button" align="right">
			
			{% if perms.categoria.add_categoria %}
			<button type="button" class="btn btn-primary" onclick="location.href='/admin/producto/categoria/add/';" title="Agregar Categoria de producto">
				<span class="glyphicon glyphicon-plus"></span>
			</button>
			{% endif %}
			
		</div>
	</form>


	<br/>

	<div align="center">
		<table id="result_list" class="table table-striped table-filter">
			<thead>
				<tr>
					<th>Nombre</th>
					<th>Acciones</th>		 
				</tr>
			</thead>

			<tbody>
				{% for categoria in object_list %}
				<tr>
					<td>{{ categoria }}</td>


					<td>
						{% if perms.categoria.change_categoria %}
						<button type="button" class="btn btn-warning btn-xs" onclick="location.href='/admin/producto/categoria/{{ categoria.id }}/';" title="Editar">
							<i class="fa fa-pencil"></i>
						</button>
						{% endif %}

						{% if perms.categoria.delete_categoria %}
						<button type="button" class="btn btn-danger btn-xs" onclick="location.href='/admin/producto/categoria/{{ categoria.id }}/delete/';" title="Borrar">
							<i class="fa fa-minus"></i>
						</button>
						{% endif %}

					</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>

	{% if is_paginated %}
	<table class="table">
		<td>
			<center>
				<ul class="pagination pagination-sm">
					{% if page_obj.has_previous %}
					<li class="previous">
						<a href="/admin/producto/categoria/?page={{ page_obj.previous_page_number }}&q={{ q }}">
							<span aria-hidden="true">&larr;</span> Primera
						</a>
					</li>

					<li>
						<a href="/admin/producto/categoria/?page={{ page_obj.previous_page_number }}&q={{ q }}">
							Anterior
						</a>
					</li> 	
					{% endif %}

					{% for page in page_obj.paginator.page_range|paginator_delimiter:page_obj.number %}
					<li>
						<a {% if page == page_obj.number %} class="active" style="background-color:#DD4814;color:white;" {% endif %} href="/admin/producto/categoria/?page={{ page }}&q={{ q }}">
							{{ page }}
						</a>
					</li>
					{% endfor %}

					{% if page_obj.has_next %}
					<li>
						<a href="/admin/producto/categoria/?page={{ page_obj.next_page_number }}&q={{ q }}">
							Siguiente
						</a>
					</li>
					
					<li class="next">
						<a href="/admin/producto/categoria/?page={{ page_obj.paginator.num_pages}}&q={{ q }}">
							&Uacute;ltima <span aria-hidden="true">&rarr;</span>
						</a>
					</li>
					{% endif %}

				</ul>
			</center>
		</td>
		<th>
			Pag. {{ page_obj.number }}/{{ page_obj.paginator.num_pages }} 
		</th>
	</table>
	{% endif %}
{% endblock %}

producto/templates/corrompidos.html
{% extends 'admin/base_site.html' %}

{% block content %}
	<p>
	{% for i in precio_compra %}
		{{ i.producto.id }} <br>
	{% endfor %}
	</p>
{% endblock %}

producto/templates/insercioninmediata_list.html
{% extends 'admin/base_site.html' %}
{% load i18n admin_static %}
{% load humanize %}
{% load my_tags %}

{% block extrastyle %}
    <link rel="stylesheet" href="{% static 'chosen/chosen.css' %}">
    <link rel="stylesheet" href="{% static 'chosen/docsupport/prism.css' %}">
{% endblock %}

{% block extrajs %}
    <script src="{% static 'chosen/chosen.jquery.js' %}"></script>
    <script src="{% static 'chosen/docsupport/prism.js' %}"></script>

    <script type="text/javascript">
        $(".chosen-select").chosen({
            disable_search_threshold: 0,
            no_results_text: "Sin resultados..",
            width: "300px",
            allow_single_deselect: true
        });
        $('.chosen-select').trigger('chosen:updated');
    </script>
{% endblock %}

{% block content %}
	<form class="form" method="get">
		<h1>Lista de Altas de productos</h1>
		<center>
			<dl>
				<table class="table-filter table table-bordered table-stripped">
					<tbody>
						<tr>

							<th style="vertical-align:middle">
								<strong> Alta:</strong>
							</th>
							<td style="vertical-align:middle">
								<input type="text" class="search-query" placeholder="Nombre o Codigo de Producto.." name="q" value="{{ q }}">
							</td>

							<th style="border-top :3px solid white; border-right :3px solid white; border-bottom :3px solid white;">
								<a class="btn btn-info" href="/admin/producto/insercioninmediata" title="Limpiar Filtros">
									<i class="fa fa-undo"></i>
								</a>
								<input type="submit" value="Buscar" class="btn btn-success" hidden="hidden" style="display: none">
							</th>
						</tr>
					</tbody>
				</table>
			</dl>
		</center>
		
		<div id="next_button" align="right">
			
			{% if perms.insercioninmediata.add_insercioninmediata %}
			<button type="button" class="btn btn-primary" onclick="location.href='/admin/producto/insercioninmediata/add/';" title="Agregar Alta de producto">
				<span class="glyphicon glyphicon-plus"></span>
			</button>
			{% endif %}
			
		</div>
	</form>


	<br/>

	<div align="center">
		<table id="result_list" class="table table-striped table-filter">
			<thead>
				<tr>
					<th>Producto</th>
					<th>Cantidad</th>
					<th>Observacion</th>
					<th>Fecha</th>
					<th>Acciones</th>		 
				</tr>
			</thead>

			<tbody>
				{% for insercioninmediata in object_list %}
				<tr>
					<td>{{ insercioninmediata.producto }}</td>
					<td>{{ insercioninmediata.cantidad|floatformat:"0"|intcomma|default_if_none:"&nbsp;" }}</td>
					<td>{{ insercioninmediata.observacion }}</td>
					<td>{{ insercioninmediata.fecha_hora }}</td>


					<td>
						{% if perms.insercioninmediata.change_insercioninmediata %}
						<button type="button" class="btn btn-warning btn-xs" onclick="location.href='/admin/producto/insercioninmediata/{{ insercioninmediata.id }}/';" title="Editar">
							<i class="fa fa-pencil"></i>
						</button>
						{% endif %}

						{% if perms.insercioninmediata.delete_insercioninmediata %}
						<button type="button" class="btn btn-danger btn-xs" onclick="location.href='/admin/producto/insercioninmediata/{{ insercioninmediata.id }}/delete/';" title="Borrar">
							<i class="fa fa-minus"></i>
						</button>
						{% endif %}

					</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>

	{% if is_paginated %}
	<table class="table">
		<td>
			<center>
				<ul class="pagination pagination-sm">
					{% if page_obj.has_previous %}
					<li class="previous">
						<a href="/admin/producto/insercioninmediata/?page={{ page_obj.previous_page_number }}&q={{ q }}">
							<span aria-hidden="true">&larr;</span> Primera
						</a>
					</li>

					<li>
						<a href="/admin/producto/insercioninmediata/?page={{ page_obj.previous_page_number }}&q={{ q }}">
							Anterior
						</a>
					</li> 	
					{% endif %}

					{% for page in page_obj.paginator.page_range|paginator_delimiter:page_obj.number %}
					<li>
						<a {% if page == page_obj.number %} class="active" style="background-color:#DD4814;color:white;" {% endif %} href="/admin/producto/insercioninmediata/?page={{ page }}&q={{ q }}">
							{{ page }}
						</a>
					</li>
					{% endfor %}

					{% if page_obj.has_next %}
					<li>
						<a href="/admin/producto/insercioninmediata/?page={{ page_obj.next_page_number }}&q={{ q }}">
							Siguiente
						</a>
					</li>
					
					<li class="next">
						<a href="/admin/producto/insercioninmediata/?page={{ page_obj.paginator.num_pages}}&q={{ q }}">
							&Uacute;ltima <span aria-hidden="true">&rarr;</span>
						</a>
					</li>
					{% endif %}

				</ul>
			</center>
		</td>
		<th>
			Pag. {{ page_obj.number }}/{{ page_obj.paginator.num_pages }} 
		</th>
	</table>
	{% endif %}
{% endblock %}