caja/urls.py
from django.conf.urls import patterns, include, url

from caja.views import *

urlpatterns = [

    url(r'^aperturacaja/$', AperturaCajaListView.as_view(), name='aperturacaja_lis'),
    url(r'^cierrecaja/$', CierreCajaListView.as_view(), name='cierrecaja_lis'),

    url(r'^$', caja_presentacion),
]

ferresis/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/auth/', include("sistema.urls", namespace="cliente")),
    url(r'^admin/sistema/', include("sistema.urls", namespace="cliente")),

    url(r'^admin/caja/', include("caja.urls", namespace="cliente")),

    url(r'^admin/cliente/', include("cliente.urls", namespace="cliente")),
    url(r'^admin/proveedor/', include("proveedor.urls", namespace="proveedor")),
    url(r'^admin/producto/', include("producto.urls", namespace="producto")),
    url(r'^admin/presupuesto/', include("presupuesto.urls", namespace="presupuesto")),
    url(r'^admin/venta/', include("venta.urls", namespace="venta")),
    url(r'^admin/compra/', include("compra.urls", namespace="compra")),


    url(r'^admin/', admin.site.urls),

    url(r'^chaining/', include('smart_selects.urls')),
]

caja/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class AperturaCaja(models.Model):
	usuario = models.ForeignKey(User)
	monto = models.DecimalField(max_digits=15,decimal_places=2)
	fecha_hora = models.DateTimeField(auto_now_add=True)

	def __unicode__(self):
		return (self.usuario.get_full_name() + '-' + self.fecha_hora.strftime('%d/%m/%Y %H:%M:%S'))

	class Meta:
		verbose_name = 'Apertura de Caja'
		verbose_name_plural = 'Aperturas de Caja'


class CierreCaja(models.Model):
	usuario = models.ForeignKey(User)
	monto = models.DecimalField(max_digits=15,decimal_places=2)
	fecha_hora = models.DateTimeField(auto_now_add=True)

	def __unicode__(self):
		return (self.usuario.get_full_name() + '-' + self.fecha_hora.strftime('%d/%m/%Y %H:%M:%S'))

	class Meta:
		verbose_name = 'Cierre de Caja'
		verbose_name_plural = 'Cierres de Caja'

caja/forms.py
from dal import autocomplete
from django import forms
from caja.models import *


class AperturaCajaForm(forms.ModelForm):
    class Meta:
        model = AperturaCaja
        fields = ('__all__' )
        widgets = { 
            "monto":forms.TextInput(attrs={'style':'text-align:right','size':'12','class':'auto','data-a-sep':'.','data-a-dec':','}),
        }

class CierreCajaForm(forms.ModelForm):
    class Meta:
        model = CierreCaja
        fields = ('__all__' )
        widgets = { 
            "monto":forms.TextInput(attrs={'style':'text-align:right','size':'12','class':'auto','data-a-sep':'.','data-a-dec':','}),
        }

caja/views.py
from django.shortcuts import render, render_to_response
from django.template import RequestContext
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from django.utils.decorators import method_decorator
from django.contrib.admin.views.decorators import staff_member_required

from django.db.models import Q

from extra.globals import *

from django.contrib.auth.models import User
from caja.models import *
# Create your views here.

class AperturaCajaListView(ListView):
    model = AperturaCaja
    template_name = "aperturacaja_list.html"
    paginate_by = 30

    def get_queryset(self):
        aperturascajas = AperturaCaja.objects.all()

        usuario_id=self.request.GET.get('usuario_id','')
        if usuario_id !='':
            aperturascajas = aperturascajas.filter(usuario_id = usuario_id)

        return aperturascajas.order_by('-id')

    def get_context_data(self, **kwargs):
        context = super(AperturaCajaListView, self).get_context_data(**kwargs)
        context['usuarios'] = User.objects.all()
        context['usuario_id'] = int(self.request.GET.get('usuario_id','')) if (self.request.GET.get('usuario_id','') != '') else ''
        return context

    @method_decorator(staff_member_required)
    def dispatch(self, *args, **kwargs):
        return super(AperturaCajaListView, self).dispatch(*args, **kwargs)


class CierreCajaListView(ListView):
    model = CierreCaja
    template_name = "cierrecaja_list.html"
    paginate_by = 30

    def get_queryset(self):
        cierrescajas = CierreCaja.objects.all()

        usuario_id=self.request.GET.get('usuario_id','')
        if usuario_id !='':
            cierrescajas = cierrescajas.filter(usuario_id = usuario_id)

        return cierrescajas.order_by('-id')

    def get_context_data(self, **kwargs):
        context = super(CierreCajaListView, self).get_context_data(**kwargs)
        context['usuarios'] = User.objects.all()
        context['usuario_id'] = int(self.request.GET.get('usuario_id','')) if (self.request.GET.get('usuario_id','') != '') else ''
        return context

    @method_decorator(staff_member_required)
    def dispatch(self, *args, **kwargs):
        return super(CierreCajaListView, self).dispatch(*args, **kwargs)


def caja_presentacion(request):
    context = RequestContext(request)
    titulo="CAJA"
    descripcion=".."
    return render_to_response('admin/presentacion.html', {'titulo': titulo, 'descripcion': descripcion}, context)

caja/templates/aperturacaja_list.html
{% extends 'admin/base_site.html' %}
{% load i18n admin_static %}
{% load humanize %}
{% load my_tags %}

{% block extrastyle %}
    <link rel="stylesheet" href="{% static 'chosen/chosen.css' %}">
    <link rel="stylesheet" href="{% static 'chosen/docsupport/prism.css' %}">
{% endblock %}

{% block extrajs %}
    <script src="{% static 'chosen/chosen.jquery.js' %}"></script>
    <script src="{% static 'chosen/docsupport/prism.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/autoNumeric.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/decimales.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.maskedinput.min.js' %}"></script>
    <script type="text/javascript">
        $(".chosen-select").chosen({
            disable_search_threshold: 0,
            no_results_text: "Sin resultados..",
            width: "300px",
            allow_single_deselect: true
        });
        $('.chosen-select').trigger('chosen:updated');
    </script>
{% endblock %}

{% block content %}
	<form class="form" method="get">
		<h1>Lista de Aperturas de Caja</h1>
		<center>
			<dl>
				<table class="table-filter table table-bordered table-stripped">
					<tbody>
						<tr>

							<th style="vertical-align:middle">
							    <strong> Usuario:</strong>
							</th>
							<td style="vertical-align:middle">
							    <select class="chosen-select" data-placeholder="Seleccione un usuario.." name="usuario_id" value="{{ usuario_id }}" onchange="this.form.submit();">
							        <option value=""></option>
							        {% for usuario in usuarios %}
							            <option {% if usuario.pk == usuario_id %} selected {% endif %} value="{{ usuario.id }}">{{ usuario }}</option>
							        {% endfor %}
							    </select>
							</td>

							<th style="border-top :3px solid white; border-right :3px solid white; border-bottom :3px solid white;">
								<a class="btn btn-info" href="/admin/caja/aperturacaja" title="Limpiar Filtros">
									<i class="fa fa-undo"></i>
								</a>
								<input type="submit" value="Buscar" class="btn btn-success" hidden="hidden" style="display: none">
							</th>
						</tr>
					</tbody>
				</table>
			</dl>
		</center>
		
		<div id="next_button" align="right">
			
			{% if perms.aperturacaja.add_aperturacaja %}
			<button type="button" class="btn btn-primary" onclick="location.href='/admin/caja/aperturacaja/add/';" title="Agregar Apertura de caja">
				<span class="glyphicon glyphicon-plus"></span>
			</button>
			{% endif %}
			
		</div>
	</form>


	<br/>

	<div align="center">
		<table id="result_list" class="table table-striped table-filter">
			<thead>
				<tr>
					<th>Usuario</th>
					<th>Monto</th>
					<th>Fecha</th>
					<th>Acciones</th>		 
				</tr>
			</thead>

			<tbody>
				{% for aperturacaja in object_list %}
				<tr>
					<td>{% if aperturacaja.usuario.get_full_name != '' %} {{ aperturacaja.usuario.get_full_name }} {% else %} {{ aperturacaja.usuario }} {% endif %}</td>
					<td>{{ aperturacaja.monto|floatformat:"0"|intcomma|default_if_none:"&nbsp;" }}</td>
					<td>{{ aperturacaja.fecha_hora }}</td>


					<td>
						{% if perms.aperturacaja.change_aperturacaja %}
						<button type="button" class="btn btn-warning btn-xs" onclick="location.href='/admin/caja/aperturacaja/{{ aperturacaja.id }}/';" title="Editar">
							<i class="fa fa-pencil"></i>
						</button>
						{% endif %}

						{% if perms.aperturacaja.delete_aperturacaja %}
						<button type="button" class="btn btn-danger btn-xs" onclick="location.href='/admin/caja/aperturacaja/{{ aperturacaja.id }}/delete/';" title="Borrar">
							<i class="fa fa-minus"></i>
						</button>
						{% endif %}

					</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>

	{% if is_paginated %}
	<table class="table">
		<td>
			<center>
				<ul class="pagination pagination-sm">
					{% if page_obj.has_previous %}
					<li class="previous">
						<a href="/admin/caja/aperturacaja/?page={{ page_obj.previous_page_number }}&usuario_id={{ usuario_id }}">
							<span aria-hidden="true">&larr;</span> Primera
						</a>
					</li>

					<li>
						<a href="/admin/caja/aperturacaja/?page={{ page_obj.previous_page_number }}&usuario_id={{ usuario_id }}">
							Anterior
						</a>
					</li> 	
					{% endif %}

					{% for page in page_obj.paginator.page_range|paginator_delimiter:page_obj.number %}
					<li>
						<a {% if page == page_obj.number %} class="active" style="background-color:#DD4814;color:white;" {% endif %} href="/admin/caja/aperturacaja/?page={{ page }}&usuario_id={{ usuario_id }}">
							{{ page }}
						</a>
					</li>
					{% endfor %}

					{% if page_obj.has_next %}
					<li>
						<a href="/admin/caja/aperturacaja/?page={{ page_obj.next_page_number }}&usuario_id={{ usuario_id }}">
							Siguiente
						</a>
					</li>
					
					<li class="next">
						<a href="/admin/caja/aperturacaja/?page={{ page_obj.paginator.num_pages}}&usuario_id={{ usuario_id }}">
							&Uacute;ltima <span aria-hidden="true">&rarr;</span>
						</a>
					</li>
					{% endif %}

				</ul>
			</center>
		</td>
		<th>
			Pag. {{ page_obj.number }}/{{ page_obj.paginator.num_pages }} 
		</th>
	</table>
	{% endif %}
{% endblock %}

caja/templates/cierrecaja_list.html
{% extends 'admin/base_site.html' %}
{% load i18n admin_static %}
{% load humanize %}
{% load my_tags %}

{% block extrastyle %}
    <link rel="stylesheet" href="{% static 'chosen/chosen.css' %}">
    <link rel="stylesheet" href="{% static 'chosen/docsupport/prism.css' %}">
{% endblock %}

{% block extrajs %}
    <script src="{% static 'chosen/chosen.jquery.js' %}"></script>
    <script src="{% static 'chosen/docsupport/prism.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/autoNumeric.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/decimales.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.maskedinput.min.js' %}"></script>
    <script type="text/javascript">
        $(".chosen-select").chosen({
            disable_search_threshold: 0,
            no_results_text: "Sin resultados..",
            width: "300px",
            allow_single_deselect: true
        });
        $('.chosen-select').trigger('chosen:updated');
    </script>
{% endblock %}

{% block content %}
	<form class="form" method="get">
		<h1>Lista de Cierres de Caja</h1>
		<center>
			<dl>
				<table class="table-filter table table-bordered table-stripped">
					<tbody>
						<tr>

							<th style="vertical-align:middle">
							    <strong> Usuario:</strong>
							</th>
							<td style="vertical-align:middle">
							    <select class="chosen-select" data-placeholder="Seleccione un usuario.." name="usuario_id" value="{{ usuario_id }}" onchange="this.form.submit();">
							        <option value=""></option>
							        {% for usuario in usuarios %}
							            <option {% if usuario.pk == usuario_id %} selected {% endif %} value="{{ usuario.id }}">{{ usuario }}</option>
							        {% endfor %}
							    </select>
							</td>

							<th style="border-top :3px solid white; border-right :3px solid white; border-bottom :3px solid white;">
								<a class="btn btn-info" href="/admin/caja/cierrecaja" title="Limpiar Filtros">
									<i class="fa fa-undo"></i>
								</a>
								<input type="submit" value="Buscar" class="btn btn-success" hidden="hidden" style="display: none">
							</th>
						</tr>
					</tbody>
				</table>
			</dl>
		</center>
		
		<div id="next_button" align="right">
			
			{% if perms.cierrecaja.add_cierrecaja %}
			<button type="button" class="btn btn-primary" onclick="location.href='/admin/caja/cierrecaja/add/';" title="Agregar Cierre de caja">
				<span class="glyphicon glyphicon-plus"></span>
			</button>
			{% endif %}
			
		</div>
	</form>


	<br/>

	<div align="center">
		<table id="result_list" class="table table-striped table-filter">
			<thead>
				<tr>
					<th>Usuario</th>
					<th>Monto</th>
					<th>Fecha</th>
					<th>Acciones</th>		 
				</tr>
			</thead>

			<tbody>
				{% for cierrecaja in object_list %}
				<tr>
					<td>{% if cierrecaja.usuario.get_full_name != '' %} {{ cierrecaja.usuario.get_full_name }} {% else %} {{ cierrecaja.usuario }} {% endif %}</td>
					<td>{{ cierrecaja.monto|floatformat:"0"|intcomma|default_if_none:"&nbsp;" }}</td>
					<td>{{ cierrecaja.fecha_hora }}</td>


					<td>
						{% if perms.cierrecaja.change_cierrecaja %}
						<button type="button" class="btn btn-warning btn-xs" onclick="location.href='/admin/caja/cierrecaja/{{ cierrecaja.id }}/';" title="Editar">
							<i class="fa fa-pencil"></i>
						</button>
						{% endif %}

						{% if perms.cierrecaja.delete_cierrecaja %}
						<button type="button" class="btn btn-danger btn-xs" onclick="location.href='/admin/caja/cierrecaja/{{ cierrecaja.id }}/delete/';" title="Borrar">
							<i class="fa fa-minus"></i>
						</button>
						{% endif %}

					</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>

	{% if is_paginated %}
	<table class="table">
		<td>
			<center>
				<ul class="pagination pagination-sm">
					{% if page_obj.has_previous %}
					<li class="previous">
						<a href="/admin/caja/cierrecaja/?page={{ page_obj.previous_page_number }}&usuario_id={{ usuario_id }}">
							<span aria-hidden="true">&larr;</span> Primera
						</a>
					</li>

					<li>
						<a href="/admin/caja/cierrecaja/?page={{ page_obj.previous_page_number }}&usuario_id={{ usuario_id }}">
							Anterior
						</a>
					</li> 	
					{% endif %}

					{% for page in page_obj.paginator.page_range|paginator_delimiter:page_obj.number %}
					<li>
						<a {% if page == page_obj.number %} class="active" style="background-color:#DD4814;color:white;" {% endif %} href="/admin/caja/cierrecaja/?page={{ page }}&usuario_id={{ usuario_id }}">
							{{ page }}
						</a>
					</li>
					{% endfor %}

					{% if page_obj.has_next %}
					<li>
						<a href="/admin/caja/cierrecaja/?page={{ page_obj.next_page_number }}&usuario_id={{ usuario_id }}">
							Siguiente
						</a>
					</li>
					
					<li class="next">
						<a href="/admin/caja/cierrecaja/?page={{ page_obj.paginator.num_pages}}&usuario_id={{ usuario_id }}">
							&Uacute;ltima <span aria-hidden="true">&rarr;</span>
						</a>
					</li>
					{% endif %}

				</ul>
			</center>
		</td>
		<th>
			Pag. {{ page_obj.number }}/{{ page_obj.paginator.num_pages }} 
		</th>
	</table>
	{% endif %}
{% endblock %}